### ISSUE TITLE
Any attempt to open the debugger throws a NetworkOnMainThread exception

### ISSUE THREAD

**Issue by aem** [callstack-io/haul#96]
I apologize because I don't have a solid repro other than running my project, but I have narrowed it down to Haul because switching back to the react-native packager allows the app to function properly. 

### Current Behavior

When connecting to the remote debugger, the app crashes with a `NetworkOnMainThreadException`:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.hubspot.android.debug, PID: 13213
                  android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@bdb46cb -- permission denied for window type 2003
                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:703)
                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                      at android.app.Dialog.show(Dialog.java:322)
                      at com.facebook.react.devsupport.DevSupportManagerImpl.showProgressDialog(DevSupportManagerImpl.java:808)
                      at com.facebook.react.devsupport.DevSupportManagerImpl.reloadJSFromServer(DevSupportManagerImpl.java:813)
                      at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:648)
                      at com.facebook.react.ReactInstanceManager$3$1.run(ReactInstanceManager.java:420)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
To compound this problem, because the debugger tries to auto-reconnect, the only way to get the app to work is to uninstall and reinstall, otherwise this will get triggered on every launch.

### Expected Behavior

I should be able to open the chrome debugger

### Haul Configuration (webpack.haul.js)

```
module.exports = ({ platform }, { resolve }) => ({
  entry: `./index.${platform}.js`,
  resolve: Object.assign(resolve, {
    alias: Object.assign({
      Immutable: 'immutable'
    }, resolve.alias || {}, myAliases)
  })
});
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  latest
| react-native     |  0.43.0
| node             | 7.8.0
| npm or yarn      | yarn 0.21.3

**Comment by satya164** [comment]
Does your app have the `Draw over other apps` permission?

**Comment by aem** [comment]
Yep

**Comment by satya164** [comment]
Can you double check? Because according to the error message, it does not.

**Comment by aem** [comment]
Ah, sorry. I posted the wrong stack trace, still had that on my clipboard from earlier. I've left the office for the day but tomorrow I can get the correct one in here

**Comment by grabbou** [comment]
We were experiencing similar issues earlier today, I'll debug them on device in the morning.

**Comment by aem** [comment]
Here's the crash:
<details>
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.hubspot.android.debug, PID: 3154
                  android.os.NetworkOnMainThreadException
                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
                      at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
                      at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
                      at okio.Okio$1.write(Okio.java:78)
                      at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
                      at okio.RealBufferedSink.emit(RealBufferedSink.java:178)
                      at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
                      at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
                      at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
                      at com.facebook.react.devsupport.JSDebuggerWebSocketClient.closeQuietly(JSDebuggerWebSocketClient.java:144)
                      at com.facebook.react.devsupport.WebsocketJavaScriptExecutor$3.run(WebsocketJavaScriptExecutor.java:146)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
</details>

It seems like there may be more networking issues as well. Seeing hundreds of instances of this log message in the application logs: 
```
W/OkHttp: A connection to http://10.0.2.2:8081/ was leaked. Did you forget to close a response body?
```

**Comment by grabbou** [comment]
I've done some tests and managed to reproduce this crash. So far it seems to be happening only when debugger is being opened for the first time. Having it opened from previous session and running the app seems to work fine.

Looking into it now.

**Comment by aem** [comment]
Another think I'm noticing is that the debugger continually tries to load on 10.0.2.2 (which I indicated above), I have to manually change the URL to localhost

**Comment by grabbou** [comment]
That has been already fixed (see open PR).

**Comment by aem** [comment]
Oops, thanks @grabbou, didn't see the linked PR

**Comment by aem** [comment]
Looks to be more networking issues at play. Upgraded to 0.3.0 and now I see a message `CANNOT TRANSLATE guest DNS ip` logged to the *device* console (not the application logs) every 4 seconds or so. With this, I can't actually run any react native code. The app starts up fine (`reactContext` is non null, any statements in my `index.android.js` file are executed) but trying to load a component fails silently. See description of the problem here: http://stackoverflow.com/questions/43229683/react-native-component-not-mounting

**Comment by aem** [comment]
^^ after a little more playing that all looks to be related more to react-native than haul, closing this in lieu of an issue over there: https://github.com/facebook/react-native/issues/13340

**Comment by aem** [comment]
whoops. may have closed this prematurely. was this where the issue of opening the debugger causing a `NetworkOnMainThread` exception was being tracked? that's still an issue in 0.5.0

**Comment by satya164** [comment]
As per your previous reply, this is an issue in React Native and not haul. So there's not much point of keeping this issue open. It's not actionable for us.
